###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "8888",
  "idCard": "123321",
  "type": "1"
}

###
GET http://localhost:8000/member/passenger/query-list?page=1&size=3
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": "1686356508583006208",
  "name": "test",
  "idCard": "123321",
  "type": "1"
}

###
DELETE http://localhost:8000/member/passenger/delete/1686356508583006208
Content-Type: application/json
token: {{token}}
